### ISSUE TITLE
ModuleNotFoundError: No module named 'yara'

### ISSUE THREAD

**Issue by diego-betto** [kavat/anubi#2]
Hi,

I've installed all deps, compiled yara, tested, and `yara-python`, tested in repl console and it works.

But if I start anubi this is the output

```
└─$ sudo python3 anubi.py
Traceback (most recent call last):
  File "/security/anubi/anubi.py", line 5, in <module>
    import config
  File "/security/anubi/config.py", line 7, in <module>
    from core.yara_scanner import YaraScan
  File "/security/anubi/core/yara_scanner.py", line 1, in <module>
    import yara
ModuleNotFoundError: No module named 'yara'  
```

Any hint?

**Comment by kavat** [comment]
Hi!
If you run pip3 list, can you see yara in the list?

Il giorno ven 14 giu 2024 alle 11:05 Diego Betto ***@***.***>
ha scritto:

**Comment by diego-betto** [comment]
This is the output
![image](https://github.com/kavat/anubi/assets/11378282/98aa8f31-a7e0-4ad7-b99a-d55d5cfcf81a)

**Comment by diego-betto** [comment]
Tested this way

![image](https://github.com/kavat/anubi/assets/11378282/78b29887-f92e-46e1-acdd-25219e9419e3)

**Comment by kavat** [comment]
It seems related to environment problem, because yara library is the same
loaded manually.
Do you have time for a quick google in computer sharing?

Il giorno ven 14 giu 2024 alle ore 11:17 Diego Betto <
***@***.***> ha scritto:

**Comment by diego-betto** [comment]
Sure

**Comment by kavat** [comment]
Can you send me your mail? I will call you using google :-)

Il giorno ven 14 giu 2024 alle ore 11:21 Diego Betto <
***@***.***> ha scritto:
